### ISSUE TITLE
ETH transfer

### ISSUE THREAD

**Issue by Sandeep0322** [seanjameshan/starknet.js#380] opened 2022-10-28 14:37 UTC
/Users/apple/Documents/starknet.js-workshop/node_modules/starknet/dist/provider/sequencer.js:394
                            error = new Error(message);
                                    ^

Error: REJECTED: TRANSACTION_FAILED
Error at pc=0:91:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:739)
Unknown location (pc=0:682)
Unknown location (pc=0:358)
Unknown location (pc=0:400)
Unknown location (pc=0:423)

Error in the called contract (0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7):
Error at pc=0:104:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:1678)
Unknown location (pc=0:1664)

Error in the called contract (0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7):
Error at pc=0:1344:
An ASSERT_EQ instruction failed: 10:3 != 10:2.
    at SequencerProvider.<anonymous> (/Users/apple/Documents/starknet.js-workshop/node_modules/starknet/dist/provider/sequencer.js:394:37)
    at step (/Users/apple/Documents/starknet.js-workshop/node_modules/starknet/dist/provider/sequencer.js:33:23)
    at Object.next (/Users/apple/Documents/starknet.js-workshop/node_modules/starknet/dist/provider/sequencer.js:14:53)
    at fulfilled (/Users/apple/Documents/starknet.js-workshop/node_modules/starknet/dist/provider/sequencer.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  response: [Object: null prototype] {
    tx_status: 'REJECTED',
    tx_failure_reason: [Object: null prototype] {
      code: 'TRANSACTION_FAILED',
      error_message: 'Error at pc=0:91:\n' +
        'Got an exception while executing a hint.\n' +
        'Cairo traceback (most recent call last):\n' +
        'Unknown location (pc=0:739)\n' +
        'Unknown location (pc=0:682)\n' +
        'Unknown location (pc=0:358)\n' +
        'Unknown location (pc=0:400)\n' +
        'Unknown location (pc=0:423)\n' +
        '\n' +
        'Error in the called contract (0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7):\n' +
        'Error at pc=0:104:\n' +
        'Got an exception while executing a hint.\n' +
        'Cairo traceback (most recent call last):\n' +
        'Unknown location (pc=0:1678)\n' +
        'Unknown location (pc=0:1664)\n' +
        '\n' +
        'Error in the called contract (0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7):\n' +
        'Error at pc=0:1344:\n' +
        'An ASSERT_EQ instruction failed: 10:3 != 10:2.'
    }
  }
}

**Comment by ethangao** [comment] 2022-11-04 14:42
Same error here when transfer.

**Comment by tabaktoni** [comment] 2022-12-08 22:20
Are there any updates on this issue, is it resolved with the latest releases?
If not can you give a sample of code to reproduce this locally, is it reproducible only on testnet or also on devnet?

**Comment by kcy1019** [comment] 2022-12-20 08:24
@tabaktoni For `ASSERT_EQ` error, this is reproducible in Goerli, and the cause is missing trailing `0` in `calldata`:

```typescript
const contract = new starknet.Contract(ethAbi, ethContractAddress, provider);
const call = contract.populate('transfer', [recipientAddress, amount]);

// vvv Uncommenting this line will fix the issue vvv
// call.calldata?.push(starknet.number.toBN("0x00"));

const calldata = starknet.transaction.fromCallsToExecuteCalldata([call]);
const txid = starknet.hash.calculateTransactionHash(
    senderAddress,
    version,
    calldata,
    maxFee,
    goerliChainId,
    starknet.number.toBN(await provider.getNonceForAddress(senderAddress)),
);
const signature = starknet.ec.sign(keyPair, txid);
await provider.invokeFunction({ contractAddress: senderAddress, calldata, signature }, { nonce, maxFee, version });
```

**Comment by NIC619** [comment] 2022-12-30 07:31
@kcy1019 Because type of `amount` is `Uint256` which requires two `felt` so you need to include `Uint256` struct definition in abi:
```javascript
        const ethAbi = [
            { "name": "transfer", "type": "function", "inputs": [{ "name": "recipient", "type": "felt" }, { "name": "amount", "type": "Uint256" }], "outputs": [{ "name": "success", "type": "felt" }] },
            {
                "members": [
                    {
                        "name": "low",
                        "offset": 0,
                        "type": "felt"
                    },
                    {
                        "name": "high",
                        "offset": 1,
                        "type": "felt"
                    }
                ],
                "name": "Uint256",
                "size": 2,
                "type": "struct"
            }
        ];
```

And then include both `low` and `high` values:
```javascript
const call = contract.populate('transfer', [other.address, ["1000", "0"]]);
// or
const call = contract.populate('transfer', [other.address, {
     low: uint256.bnToUint256(1000).low,
     high: uint256.bnToUint256(0).high,
}]);
```

**Comment by kcy1019** [comment] 2022-12-30 07:45
@NIC619 Thank you for the detailed explanation and the fix!

**Closed as completed** 2023-02-22 17:20 UTC
Labels: help wanted
